-   id: eos-test-check-argument-order
    name: 'EOS: TEST_CHECK_* arguments order'
    description: Checks if the arguments of TEST_CHECK_* macros are in the correct order
    entry: eos-test-check-argument-order
    language: python
    types: [text]
-   id: eos-test-ordereddict-usage
    name: 'EOS: OrderedDict usage'
    description: Checks if OrderedDict is imported, as it likely isn't needed
    entry: eos-test-ordereddict-usage
    language: python
    types: [text]
-   id: eos-test-check-references
    name: 'EOS: Check EOS references'
    description: Checks if references mentioned in the EOS source code are well formed and appear in the references.yaml file
    entry: eos-test-check-references
    language: python
    types: [text]
