on:
  pull_request:
    branches:
      - master

name: Check if pre-commit manifest is valid

jobs:
  pre-commit-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13.7"
      - run: python -m pip install pre-commit
      - run: pre-commit validate-manifest .pre-commit-hooks.yaml

